"""Export `chembl_labels.tsv`: every ChEMBL molecule label, for name resolution.

## Who this is for

A consumer holding free-text compound strings -- a screening file's
`compoundName`, a catalogue entry, a trial description -- needs to turn them into
ChEMBL ids. The RDF layer supports that in SPARQL via `skos:altLabel`, but a
resolver that is parsing and normalising thousands of strings wants a table, not a
query per string. This is that table, and it is the general half of the job: the
index is release-derived and portal-agnostic, so the parsing rules for any one
source's field conventions stay with that source.

## It records ambiguity instead of resolving it

2,607 case-folded labels name more than one molecule. Each such label gets one row
per molecule with `ambiguous=yes`, so a consumer can see the fork and decide --
prefer a preferred-name match over a synonym, prefer the parent over the salt, or
refuse to guess. Collapsing them here would hand downstream a confident wrong
answer with no way to tell.

## Normalisation is minimal and reversible

Only case folding, which is what makes `SELUMETINIB` meet `Selumetinib`. Everything
stronger -- stripping punctuation, spaces, salt prefixes, stereochemistry -- is left
to the consumer, because those rules trade recall for precision differently
depending on the field being matched, and a pre-normalised index would hide the raw
label that a human has to read when a match looks wrong. Both forms are in the file.

Usage:
    python -m opentargets.export_label_index --release 26.06
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .common import DEFAULT_RELEASE, log, read_dataset
from .transform_molecules import COLUMNS, labels_of

HEADER = [
    "label",          # the label exactly as the release spells it
    "label_folded",   # str.casefold() of the above; the join key
    "kind",           # preferred_name | synonym | trade_name
    "source",         # who the release attributes the label to
    "chembl_id",
    "molecule_name",  # the molecule's preferred name, for eyeballing a match
    "drug_type",
    "ambiguous",      # yes when label_folded names more than one molecule
]


#: Strongest first. A label that is a molecule's preferred name is better evidence
#: than the same string appearing in its synonym list.
KIND_RANK = {"preferred_name": 0, "synonym": 1, "trade_name": 2}


def build(input_dir: Path) -> tuple[list[tuple], dict]:
    data = read_dataset(input_dir, "drug_molecule", COLUMNS)
    rows: list[tuple] = []
    by_folded: dict[str, set[str]] = {}

    for batch in data.to_batches(columns=COLUMNS, batch_size=20_000):
        for row in batch.to_pylist():
            chembl_id = (row.get("id") or "").strip()
            if not chembl_id:
                continue
            name = (row.get("name") or "").strip()
            drug_type = (row.get("drugType") or "").strip()
            # Exactly one row per (folded label, molecule), keeping the strongest
            # kind. The release spells the same label as both a preferred name and
            # a synonym, and lists synonyms once per attributing source; without
            # this, joining on label_folded returns the same molecule several times
            # and a consumer counting candidates would see ambiguity that is not
            # there. The contract is: one row = one candidate molecule.
            best: dict[str, tuple] = {}
            for label, kind, source in labels_of(row):
                folded = label.casefold()
                rank = KIND_RANK[kind]
                current = best.get(folded)
                if current is None or rank < KIND_RANK[current[2]]:
                    best[folded] = (label, folded, kind, source, chembl_id,
                                    name, drug_type)
            for folded, entry in best.items():
                by_folded.setdefault(folded, set()).add(chembl_id)
                rows.append(entry)

    ambiguous = {folded for folded, ids in by_folded.items() if len(ids) > 1}
    rows = [r + ("yes" if r[1] in ambiguous else "no",) for r in rows]
    rows.sort(key=lambda r: (r[1], r[4], r[2]))
    stats = {
        "rows": len(rows),
        "distinct_labels": len(by_folded),
        "ambiguous_labels": len(ambiguous),
        "molecules": len({r[4] for r in rows}),
        "unambiguous_labels": len(by_folded) - len(ambiguous),
    }
    return rows, stats


def write(rows: list[tuple], out_path: Path, release: str, stats: dict) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="") as out:
        out.write(f"# ChEMBL molecule label index, Open Targets Platform {release}\n")
        out.write("# Generated by python -m opentargets.export_label_index\n")
        out.write("# Join on label_folded. A label with ambiguous=yes has one row per\n")
        out.write("# molecule it names; resolve or refuse, but do not pick blindly.\n")
        out.write(f"# {stats['rows']:,} rows, {stats['distinct_labels']:,} distinct "
                  f"folded labels ({stats['ambiguous_labels']:,} ambiguous), "
                  f"{stats['molecules']:,} molecules\n")
        out.write("\t".join(HEADER) + "\n")
        for row in rows:
            # Labels are free text from ChEMBL; a stray tab or newline would shift
            # every later column. Replaced rather than quoted, so the file stays a
            # plain TSV that `cut` and `awk` read correctly.
            out.write("\t".join(
                str(value).replace("\t", " ").replace("\n", " ").replace("\r", " ")
                for value in row) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--release", default=DEFAULT_RELEASE)
    parser.add_argument("--indir", type=Path, default=None)
    parser.add_argument("--workdir", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=None,
                        help="Output TSV (default: <workdir>/exports/chembl_labels.tsv)")
    args = parser.parse_args()

    indir = args.indir or Path("opentargets/input") / args.release
    workdir = args.workdir or Path("opentargets") / args.release / "data"
    out_path = args.out or workdir / "exports" / "chembl_labels.tsv"

    log(f"Building the ChEMBL label index from {indir}")
    rows, stats = build(indir)
    write(rows, out_path, args.release, stats)
    log(f"  {stats['rows']:,} rows over {stats['molecules']:,} molecules")
    log(f"  {stats['distinct_labels']:,} distinct folded labels: "
        f"{stats['unambiguous_labels']:,} unambiguous, "
        f"{stats['ambiguous_labels']:,} ambiguous")
    log(f"  -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
