"""Compare releases and write retired pathways plus a Markdown report.

Append the Turtle to urn:sagebrain:reactome:retired. Successors inferred by
exact label match are optional (--infer-successor-by-name), not authoritative."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .common import (
    HUMAN,
    IngestError,
    SpeciesFilter,
    TurtleWriter,
    literal,
    log,
    pathway_curie,
    read_tsv,
)


RETIRED_GRAPH = "urn:sagebrain:reactome:retired"


def load_pathways(path: Path, species: str) -> dict[str, str]:
    """{stable_id: name} for one release, filtered with the shared species filter."""
    species_filter = SpeciesFilter(species_name=species)
    pathways: dict[str, str] = {}
    for row in read_tsv(path, expected_fields=3, has_header=False):
        if species_filter.keep_row(row, species_column=3):
            pathways[row[0].strip()] = row[1].strip()
    if not pathways:
        raise IngestError(f"No {species!r} pathways found in {path}.")
    return pathways


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--previous", type=Path, required=True,
                        help="ReactomePathways.txt from release N-1")
    parser.add_argument("--current", type=Path, required=True,
                        help="ReactomePathways.txt from release N")
    parser.add_argument("--previous-version", required=True)
    parser.add_argument("--current-version", required=True)
    parser.add_argument("--outdir", type=Path, required=True,
                        help="ttl directory -- only the retired-pathways .ttl goes here")
    parser.add_argument("--report", type=Path, default=None,
                        help="Where to write the markdown diff report (default: a sibling "
                             "'reports/' next to --outdir, not the ttl directory itself). "
                             "Point this at reactome/manifests/ to commit the ledger.")
    parser.add_argument("--species", default=HUMAN)
    parser.add_argument("--infer-successor-by-name", action="store_true",
                        help="Emit dcterms:isReplacedBy where a retired pathway's exact label "
                             "reappears under an ID new in release N (heuristic; off by default)")
    args = parser.parse_args()

    args.outdir.mkdir(parents=True, exist_ok=True)
    previous_version = args.previous_version.lstrip("v").upper()
    current_version = args.current_version.lstrip("v").upper()

    previous = load_pathways(args.previous, args.species)
    current = load_pathways(args.current, args.species)
    log(f"V{previous_version}: {len(previous):,} pathways | "
        f"V{current_version}: {len(current):,} pathways")

    retired = sorted(set(previous) - set(current))
    added = sorted(set(current) - set(previous))
    renamed = sorted(
        stable_id for stable_id in set(previous) & set(current)
        if previous[stable_id] != current[stable_id]
    )
    log(f"  retired: {len(retired):,}")
    log(f"  added:   {len(added):,}")
    log(f"  relabelled (same ID, new name): {len(renamed):,}")

    successors: dict[str, str] = {}
    if args.infer_successor_by_name:
        new_by_name = {current[stable_id]: stable_id for stable_id in added}
        for stable_id in retired:
            candidate = new_by_name.get(previous[stable_id])
            if candidate:
                successors[stable_id] = candidate
        log(f"  inferred successors by exact label match: {len(successors):,}")

    output = args.outdir / f"retired_v{previous_version}_to_v{current_version}.ttl"
    with open(output, "w", encoding="utf-8") as handle:
        writer = TurtleWriter(handle)
        writer.comment(
            f"Pathways present in Reactome V{previous_version} but absent in "
            f"V{current_version}.\n"
            f"Load into <{RETIRED_GRAPH}> with POST (append), never PUT:\n"
            "that graph is persistent and cumulative across releases.\n"
            "The label and last-seen release are retained so a lookup of a dead ID can\n"
            "say what it used to be instead of dead-ending.\n"
            "Generated by reactome/release_diff.py"
        )
        if not retired:
            writer.comment("No pathways were retired in this release.")
        for stable_id in retired:
            pairs = [
                ("a", "biolink:Pathway"),
                ("rdfs:label", literal(previous[stable_id])),
                ("biolink:in_taxon", SpeciesFilter(species_name=args.species).taxon_curie),
                ("owl:deprecated", "true"),
                ("sagebrain:last_seen_in_release", literal(f"V{previous_version}")),
                ("sagebrain:retired_in_release", literal(f"V{current_version}")),
            ]
            if stable_id in successors:
                pairs.append(("dcterms:isReplacedBy", pathway_curie(successors[stable_id])))
            writer.statements(pathway_curie(stable_id), pairs)

    report = args.report or (
        args.outdir.parent / "reports" / f"release_diff_v{previous_version}_to_v{current_version}.md"
    )
    report.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Reactome V{previous_version} -> V{current_version} diff ({args.species})",
        "",
        f"- retired: **{len(retired)}**",
        f"- added: **{len(added)}**",
        f"- relabelled (same ID, new name): **{len(renamed)}**",
        "",
    ]
    if retired:
        lines += ["## Retired", "", "| Stable ID | Last label | Successor |", "|---|---|---|"]
        lines += [
            f"| `{s}` | {previous[s]} | {'`' + successors[s] + '`' if s in successors else '--'} |"
            for s in retired
        ]
        lines.append("")
    if renamed:
        lines += ["## Relabelled", "", "| Stable ID | Old label | New label |", "|---|---|---|"]
        lines += [f"| `{s}` | {previous[s]} | {current[s]} |" for s in renamed[:200]]
        lines.append("")
    report.write_text("\n".join(lines), encoding="utf-8")

    log(f"\nWrote {writer.triples:,} triples -> {output}")
    log(f"Wrote diff report -> {report}")
    log(f"\nLoad with: python -m reactome.load_graph is per-release only; append this "
        f"file to <{RETIRED_GRAPH}> (POST, not PUT).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
