"""Write pathway-to-GO skos:closeMatch links for the filtered pathway set.

Pathways2GoTerms_human.txt has a header. GO and Reactome pathways are not
coextensive, so owl:equivalentClass would be incorrect."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .common import (
    HUMAN,
    IngestError,
    TurtleWriter,
    go_curie,
    log,
    pathway_curie,
    read_tsv,
    taxon_curie_for_species,
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--indir", type=Path, required=True)
    parser.add_argument("--outdir", type=Path, required=True)
    parser.add_argument("--interim-dir", type=Path, default=None,
                        help="Where pathway_ids.txt is read from (default: a sibling "
                             "'interim/' next to --outdir)")
    parser.add_argument("--species", default=HUMAN)
    args = parser.parse_args()

    args.outdir.mkdir(parents=True, exist_ok=True)
    interim_dir = args.interim_dir or (args.outdir.parent / "interim")
    taxon = taxon_curie_for_species(args.species)

    ids_path = interim_dir / "pathway_ids.txt"
    if not ids_path.exists():
        raise IngestError(
            f"Missing {ids_path}. Run transform_pathways.py first."
        )
    in_scope = {line.strip() for line in ids_path.read_text().splitlines() if line.strip()}
    log(f"Loaded {len(in_scope):,} in-scope pathway IDs")

    source = args.indir / "Pathways2GoTerms_human.txt"
    mappings: dict[str, set[str]] = {}
    out_of_scope = 0
    rows = 0

    for row in read_tsv(source, expected_fields=3, has_header=True):
        stable_id, _name, go_id = (value.strip() for value in row)
        rows += 1
        if stable_id not in in_scope:
            out_of_scope += 1
            continue
        mappings.setdefault(stable_id, set()).add(go_curie(go_id))

    total = sum(len(v) for v in mappings.values())
    log(f"  rows: {rows:,}")
    log(f"  pathways with a GO term: {len(mappings):,} ({total:,} crosswalk edges)")
    if out_of_scope:
        log(f"  dropped {out_of_scope:,} rows referencing out-of-scope pathways")
    if not mappings:
        raise IngestError(
            "No GO crosswalk rows survived filtering. Either the pathway ID set is "
            "wrong or the crosswalk file does not match this release."
        )

    output = args.outdir / "go_crosswalk.ttl"
    with open(output, "w", encoding="utf-8") as handle:
        writer = TurtleWriter(handle)
        writer.comment(
            "Reactome pathway -> GO Biological Process crosswalk.\n"
            "skos:closeMatch, NEVER owl:equivalentClass: Reactome pathways and GO BP\n"
            "terms are not co-extensive and the granularity mismatch is structural.\n"
            f"Scope: {args.species} ({taxon}).\n"
            "Generated by reactome/transform_go.py"
        )
        for stable_id in sorted(mappings):
            writer.statements(
                pathway_curie(stable_id),
                [("skos:closeMatch", go) for go in sorted(mappings[stable_id])],
            )

    log(f"\nWrote {writer.triples:,} triples -> {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
